### PR TITLE
Add support for typst

### PR DESCRIPTION
**Pull request by bloedboemmel**
## Description

I want to support the new markdown-Language Typst

#839 

## Checklist

* [x] Have you read the [guidelines on contributing code to LT<sub>E</sub>X](https://valentjn.github.io/ltex/vscode-ltex/contributing.html#how-to-contribute-code)?
* [x] Have you filled in all missing information in this pull request template?
* [ ] Have you written new tests for your changes, if applicable?
* [x] Do your changes pass all [code checks](https://valentjn.github.io/ltex/vscode-ltex/contributing.html#code-checks) such as linting and tests?

### CODE REVIEW

**Comment by C-Lunn** [comment]
I've compiled and installed this and it seems that on `.typ` files, the checker must be manually run each time; i.e. the `    "ltex.checkFrequency": "edit"` setting is not respected.

Any idea how to get that to work? Cheers.

**Comment by MexHigh** [comment]
Why was this closed? Perhaps I could try to implement this?

**Comment by AdiWeit** [comment]
> Why was this closed? Perhaps I could try to implement this?

There is actually a fork of this project because it seems like it is no longer maintained: https://github.com/neo-ltex/vscode-ltex
In the fork, there is an issue for this as well: https://github.com/neo-ltex/vscode-ltex/issues/23

**Comment by spitzerd** [comment]
@MexHigh and @AdiWeit 
LTeX+ supports Typst. Right now, you have to use the nightly builds, because this feature is not released yet.
See https://github.com/ltex-plus/vscode-ltex-plus/issues/74

**Pull request closed without merging**
